export const ANIMATION_TIMING = {
  HERO_SECTION: 0,
  CREATE_LINK_FORM: 0.3,
  FEATURES_PAPER: 0.6,
  FEATURES_TITLE: 0.7,
  FEATURES_CTA: 0.8,
  SOCIAL_PROOF: 0.9,
  FEATURES_LIST: 1.0,
  WHY_CHOOSE_HEADER: 1.8,
  FEATURE_CARDS: 2.1,
  CALL_TO_ACTION: 2.7,
} as const

export const ANIMATION_DURATIONS = {
  FAST: 0.4,
  NORMAL: 0.6,
  SLOW: 0.8,
} as const

export const STAGGER_DELAYS = {
  TIGHT: 0.1,
  NORMAL: 0.15,
  LOOSE: 0.2,
} as const

export const FEATURE_CARD_DELAYS = {
  LIGHTNING_FAST: ANIMATION_TIMING.FEATURE_CARDS,
  DETAILED_ANALYTICS: ANIMATION_TIMING.FEATURE_CARDS + 0.1,
  SECURE_RELIABLE: ANIMATION_TIMING.FEATURE_CARDS + 0.2,
  MOBILE_OPTIMIZED: ANIMATION_TIMING.FEATURE_CARDS + 0.3,
} as const

export const ICON_DELAYS = {
  LIGHTNING_FAST: FEATURE_CARD_DELAYS.LIGHTNING_FAST + 0.2,
  DETAILED_ANALYTICS: FEATURE_CARD_DELAYS.DETAILED_ANALYTICS + 0.2,
  SECURE_RELIABLE: FEATURE_CARD_DELAYS.SECURE_RELIABLE + 0.2,
  MOBILE_OPTIMIZED: FEATURE_CARD_DELAYS.MOBILE_OPTIMIZED + 0.2,
} as const

export const FEATURE_ITEM_DELAYS = {
  INSTANT: ANIMATION_TIMING.FEATURES_LIST,
  FREE: ANIMATION_TIMING.FEATURES_LIST + 0.1,
  ANALYTICS: ANIMATION_TIMING.FEATURES_LIST + 0.2,
  SECURE: ANIMATION_TIMING.FEATURES_LIST + 0.3,
} as const

export const BLUR_TEXT_DELAYS = {
  INSTANT: FEATURE_ITEM_DELAYS.INSTANT + 0.1,
  FREE: FEATURE_ITEM_DELAYS.FREE + 0.1,
  ANALYTICS: FEATURE_ITEM_DELAYS.ANALYTICS + 0.1,
  SECURE: FEATURE_ITEM_DELAYS.SECURE + 0.1,
  LIGHTNING_FAST: ICON_DELAYS.LIGHTNING_FAST + 0.1,
  DETAILED_ANALYTICS: ICON_DELAYS.DETAILED_ANALYTICS + 0.1,
  SECURE_RELIABLE: ICON_DELAYS.SECURE_RELIABLE + 0.1,
  MOBILE_OPTIMIZED: ICON_DELAYS.MOBILE_OPTIMIZED + 0.1,
} as const
